---
- name: Download and Install Automation Hub
  hosts: aap_ah[0]
  become: true
  vars_files: 
    - variables.yml
  roles:
    - infra.aap_utilities.aap_setup_download
    - infra.aap_utilities.aap_setup_prepare
    - infra.aap_utilities.aap_setup_install
