---
- name: Run pre-check on AAP2 selection
  ansible.builtin.import_playbook: precheck.yml
  tags: aap_precheck

- name: Run common tasks
  ansible.builtin.import_playbook: common.yml
  tags: common_tasks

- name: Setup FreeIPA Server
  ansible.builtin.import_playbook: freeipa_install.yml
  tags: freeipa_install

- name: Install Private Automation Hub
  ansible.builtin.import_playbook: ah_install.yml
  tags: ah_install

- name: Print details
  ansible.builtin.import_playbook: print_details.yml
  tags: print_details
