---
- name: Run pre-check on AAP2 selection
  ansible.builtin.import_playbook: precheck.yml
  tags: aap_precheck

- name: Run common tasks
  ansible.builtin.import_playbook: common.yml
  tags: common_tasks

- name: Install Red Hat Ansible Automation Platform
  ansible.builtin.import_playbook: aap_install.yml
  tags: aap_install

- name: Attach Subscription to Ansible Controller
  ansible.builtin.import_playbook: license.yml
  tags: attach_license

- name: Install Event Driven Automation Controller
  ansible.builtin.import_playbook: eda_install.yml
  tags: eda_install

- name: Print details
  ansible.builtin.import_playbook: print_details.yml
  tags: print_details
