---
- name: Run a pre-check on the provided AAP2 selection
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - variables.yml
  roles:
    - nshaik.aap_collection.precheck
