# -*- mode: ruby -*-
# vi: set ft=ruby :

### Load variables from the config file ###
config_file = File.join(File.dirname(__FILE__), "variables.yml")
vars = YAML.load_file(config_file)

rhel_version = vars['aap_setup_rhel_version']

Vagrant.configure("2") do |config|
  ### Global Configuration  ###
  config.vm.box = "nshaik/rhel" + rhel_version
  config.vm.box_url = "http://content.syslab.pnq2.redhat.com/content/aap/rhel" + rhel_version + "/metadata.json"
  config.vm.provider "libvirt" do |libvirt|
    libvirt.default_prefix = vars['vm_prefix'] || ""
    libvirt.memory = vars['memory']
    libvirt.cpus = vars['cpus']
  end

  ### Configuration related to AAP Cluster Nodes ###
  (1..vars['controller_nodes']).each do |i|
    config.vm.define "#{vars['ctrl_name']}#{i}" do |controller|
      controller.vm.hostname = "#{vars['ctrl_name']}#{i}.#{vars['domain']}"
      controller.vm.network "private_network", ip: "172.25.123.#{10 + i}", name: vars['libvirt_bridge']
      controller.vm.provision "shell", inline: <<-SHELL
        echo "aap_controller" | tee /etc/server_role
      SHELL
      controller.vm.provider "libvirt" do |libvirt|
        libvirt.default_prefix = ""
        libvirt.memory = vars['ctrl_memory']
        libvirt.cpus = vars['ctrl_cpus']
      end
    end
  end

  ### Configuration related to external DB ###
  config.vm.define vars['dbserver_name'] do |db|
    db.vm.hostname = "#{vars['dbserver_name']}.#{vars['domain']}"
    db.vm.network  "private_network", ip: vars['dbserver_ip'], name: vars['libvirt_bridge']
    db.vm.provision "shell", inline: <<-SHELL
      echo "aap_db" | tee /etc/server_role
    SHELL
  end

  ### Configuration related to HAProxy to Load balance AAP Nodes ###
  config.vm.define vars['lbserver_name'] do |lb|
    lb.vm.hostname = "#{vars['lbserver_name']}.#{vars['domain']}"
    lb.vm.network  "private_network", ip: vars['lbserver_ip'], name: vars['libvirt_bridge']
    lb.vm.provision "shell", inline: <<-SHELL
      echo "aap_lb" | tee /etc/server_role
    SHELL
    lb.vm.provision "ansible" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.limit = "all"
      ansible.inventory_path = "vagrant.py"
      ansible.playbook = "site.yml"
      ansible.verbose = "vv"
      if !vars['vault_password_file'].nil?
        ansible.vault_password_file = vars['vault_password_file']
      end
      #ansible.tags = "configure_aap_nodes"
    end
  end
end
