---
- name: Run pre-check on AAP2 selection
  ansible.builtin.import_playbook: precheck.yml
  tags: aap_precheck

- name: Run private key tasks
  ansible.builtin.import_playbook: private.yml
  tags: private_tasks

- name: Run common tasks
  ansible.builtin.import_playbook: common.yml
  tags: common_tasks

- name: Install Red Hat Ansible Automation Platform
  ansible.builtin.import_playbook: aap_install.yml
  tags: aap_install

    #- name: Attach Subscription to Ansible controller
    #ansible.builtin.import_playbook: license.yml
    #tags: attach_license

    #- name: Print details
    #ansible.builtin.import_playbook: print_details.yml
    #tags: print_details
