---
- name: Create Users on FreeIPA Server
  hosts: ldap_server
  become: true
  vars_files:
    - variables.yml
  roles:
    - role: nshaik.aap_collection.create_ipa_users
      when: create_ldap_users|bool
